server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  level:
    web: debug
    sql: debug
    cn.sabercon: debug
spring:
  datasource:
    url: jdbc:mysql://www.sabercon.cn:3306/megumin
    username: root
    password: sabercon20
  jpa:
    show-sql: true
  data:
    mongodb:
      host: www.sabercon.cn
      port: 27017
      database: megumin
      username: root
      password: sabercon20
      authentication-database: admin
  redis:
    host: www.sabercon.cn
    port: 6379

