server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://www.sabercon.cn:3306/megumin?serverTimezone=Asia/Shanghai
    username: root
    password: ENC(z+RhuUIJkbiC1SvLB60veNQ7af5hmZk82EHLLErazaAJ/1u8Hsq25C0ByNmZJNFo)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: www.sabercon.cn
      port: 27017
      database: megumin
      username: root
      password: ENC(z+RhuUIJkbiC1SvLB60veNQ7af5hmZk82EHLLErazaAJ/1u8Hsq25C0ByNmZJNFo)
      authentication-database: admin
  redis:
    host: www.sabercon.cn
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  level:
    web: debug
    sql: debug
    cn.sabercon: debug

